name: proof_of_concept
description: "Boneco de teste para o Mapbox Maps Flutter e Arquitetura MVVM"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  flutter_riverpod: ^2.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true